# Offense count: 1
# Configuration parameters: CountComments, ExcludedMethods.
Metrics/BlockLength:
  Max: 100

# Offense count: 60
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 154

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 15

# Offense count: 1
Metrics/AbcSize:
  Max: 25

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 20

Documentation:
  Enabled: false  

AllCops:
  Exclude:
    - 'db/schema.rb'